name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install regular and dev dependencies
      run: pip install .[dev]

    - name: Lint with flake8
      run: |
        python3 -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics src
        python3 -m flake8 --count --exit-zero --max-complexity=30 --max-line-length=100 --statistics src

    - name: Run unit tests
      run: python3 -m unittest tests/spec_*.py
